Auto deploy beta from master

diff --git a/.github/workflows/frontend-beta.yml b/.github/workflows/frontend-beta.yml
--- a/.github/workflows/frontend-beta.yml
+++ b/.github/workflows/frontend-beta.yml
@@ -1,9 +1,8 @@
 name: Deploy to Beta Site
 
 on:
-  pull_request:
+  push:
     branches: ["master"]
-    types: ["opened"]
     paths:
       - frontend/**
   workflow_dispatch:
@@ -28,14 +27,17 @@ jobs:
             git stash
 
             # Pull from git repo
-            git checkout ${{ github.event.pull_request.head.sha || 'master' }} || true # Force return true so exit code is not 1
+            git checkout master || true # Force return true so exit code is not 1
             git pull
+
+            # Clear space
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker image prune -f
 
             # Build
             cd frontend
             echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S bash ./build.sh
             cd ..
-            echo "${{ secrets.SUDO_PASSWORD }}" | sudo docker-compose -f ./docker-compose.prod.yml up -d frontend
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker-compose -f ./docker-compose.prod.yml up -d frontend
 
             # Restore changes
             git stash pop || true # Force return true in case no changes stashed
